#
#
# Example config.  Fill out and rename config.yaml
# EZPZ!
#
#


# OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
oauth: oauth:[YOUR_OAUTH_TOKEN_SECRET]
channel: "[YOUR_TWITCH_CHANNEL_NAME]"
bot_name: "[YOUR_TWITCH_BOT_NAME]"



# Commands - the real stuff
commands:
  - optionalName: "press some keys command"
    # You can find your reward ID here: https://www.instafluff.tv/TwitchCustomRewardID/?channel=yourchannel
    twitchRewardId: "[ID from Twitch]"
    action:
      # A string to represent hotkeys. Must follow the Java KeyStroke format:
      # See: https://docs.oracle.com/javase/7/docs/api/javax/swing/KeyStroke.html#getKeyStroke(java.lang.String)
      # example: shift control alt command A
      keysToPress: "shift alt A"

  - optionalName: "whisper to your bot command"
    twitchRewardId: "[Another ID from Twitch]"
    action:
      messageToWhisper: "Whispery whisper glam"

  - optionalName: "Perform one random action command"
    twitchRewardId: "[A third ID from Twitch]"
    action:
      name: Perform some random silly thing
      performAtRandom:
        - name: action A
          messageToWhisper: "Hey bot, play sound A"

        - name: action B
          messageToWhisper: "Hey bot, play sound B"

        - name: action C
          keysToPress: "shift alt B"